/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De5;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class De5 extends javax.swing.JFrame {

    Client cliensocket;

    /**
     * Creates new form myJFrame
     *
     * @throws java.io.IOException
     */
    public De5() throws IOException {
//        clientSocket.Excute(jTextField_mssv.getText());
        initComponents();
        this.cliensocket = new Client("localhost", 5000);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Label_mssv = new javax.swing.JLabel();
        TextFile_mssv = new javax.swing.JTextField();
        Button_xem = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_mssv = new javax.swing.JLabel();
        jLabel_hoten = new javax.swing.JLabel();
        jLabel_phai = new javax.swing.JLabel();
        jLabel_NoiSinh = new javax.swing.JLabel();
        jLabel_nganh = new javax.swing.JLabel();
        jLabel_lop = new javax.swing.JLabel();
        jlabel_khoa = new javax.swing.JLabel();
        Label_htmmsv = new javax.swing.JLabel();
        Label_hthoten = new javax.swing.JLabel();
        Label_htPhái = new javax.swing.JLabel();
        Label_htnganh = new javax.swing.JLabel();
        Label_htnoisinh = new javax.swing.JLabel();
        Label_htlop = new javax.swing.JLabel();
        Label_htKhoa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label_tbtichluy = new javax.swing.JLabel();
        Label_TCtichluyhe4 = new javax.swing.JLabel();
        Label_TCtichluy = new javax.swing.JLabel();
        Label_Somondahoc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelChidanghoc = new javax.swing.JLabel();
        jLabelChiconlai = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_mssv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tieuChi = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabelCondition = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_tracuu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.CardLayout());

        Label_mssv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_mssv.setText("Mã Số Sinh Viên");

        TextFile_mssv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextFile_mssv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFile_mssvActionPerformed(evt);
            }
        });

        Button_xem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_xem.setText("Xem");
        Button_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_xemActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel_mssv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel_mssv.setText("Mã số sinh viên : ");

        jLabel_hoten.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_hoten.setText("Họ tên :");

        jLabel_phai.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_phai.setText("Phái :");

        jLabel_NoiSinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_NoiSinh.setText("Nơi sinh :");

        jLabel_nganh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_nganh.setText("Ngành :");

        jLabel_lop.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_lop.setText("Lớp :");

        jlabel_khoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlabel_khoa.setText("Khoa :");

        Label_htmmsv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_htmmsv.setText(" ");

        Label_hthoten.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_hthoten.setText(" ");

        Label_htPhái.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_htPhái.setText(" ");

        Label_htnganh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_htnganh.setText(" ");

        Label_htnoisinh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_htnoisinh.setText(" ");

        Label_htlop.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_htlop.setText(" ");

        Label_htKhoa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_htKhoa.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel_hoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_mssv))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_nganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_NoiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_phai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_lop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlabel_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_htlop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_htnganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_htnoisinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_htPhái, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_hthoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_htmmsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_htKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_htmmsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_mssv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_hthoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_hoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_phai))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Label_htPhái, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_NoiSinh)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_nganh)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_lop)
                        .addGap(24, 24, 24)
                        .addComponent(jlabel_khoa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_htnoisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_htnganh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_htlop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label_htKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin", jPanel1);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("Trung bình tích lũy :");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Trung bình tích lũy hệ 4 :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Tín chỉ tích lũy :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Số môn đã học :");

        Label_tbtichluy.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_tbtichluy.setText(" ");

        Label_TCtichluyhe4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_TCtichluyhe4.setText(" ");

        Label_TCtichluy.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_TCtichluy.setText(" ");

        Label_Somondahoc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Label_Somondahoc.setText(" ");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Số tín chỉ đang học :");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Số tín chỉ còn lại : ");

        jLabelChidanghoc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelChidanghoc.setText(" ");

        jLabelChiconlai.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelChiconlai.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Somondahoc, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(Label_TCtichluyhe4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_TCtichluy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_tbtichluy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(305, 305, 305))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelChiconlai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabelChidanghoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Label_tbtichluy))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Label_TCtichluyhe4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Label_TCtichluy))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Somondahoc)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelChidanghoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelChiconlai))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê", jPanel5);

        jScrollPane3.setToolTipText("");

        jTable3.getTableHeader().setFont(new java.awt.Font("Arial", 0, 16));
        jTable3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tất cả các môn", "Điểm"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Điểm các môn", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Label_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFile_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(Button_xem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFile_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_xem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("Mã số sinh viên");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("Tiêu chí");

        jTextField_mssv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField_mssv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mssvActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton1.setText("Xem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable1.getTableHeader().setFont(new java.awt.Font("Arial", 0, 16));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cao hơn", "Điểm"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tieuChi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tieuChi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn tiêu chí", "Khóa", "Ngành", "Khoa" }));
        tieuChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieuChiActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable2.getTableHeader().setFont(new java.awt.Font("Arial", 0, 16));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thấp hơn", "Điểm"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Thứ tự theo");

        jLabelCondition.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCondition.setText(" ");

        jLabelPosition.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPosition.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_mssv, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(tieuChi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCondition)
                            .addComponent(jLabelPosition))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card3");

        jMenu_tracuu.setText("Tra cứu");
        jMenu_tracuu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu_tracuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_tracuuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_tracuu);

        jMenu1.setText("Xếp hạng");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_tracuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_tracuuMouseClicked
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jMenu_tracuuMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void Button_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_xemActionPerformed
        String mssv = TextFile_mssv.getText();
        try {

//            cliensocket.out.write(mssv);       
//            cliensocket.Sent(cliensocket.out); 
            String datasend = "button1#" + mssv;
            cliensocket.out.write(datasend);
            cliensocket.Sent(cliensocket.out);
            if (cliensocket.check(cliensocket.in).equals("404")) {
                JOptionPane.showMessageDialog(null, "Mã số sinh viên không tồn tại");
            } else {
//                System.out.println(cliensocket.getInfo(cliensocket.in, cliensocket.out));
                String tmp = cliensocket.getInfo(cliensocket.in, cliensocket.out);
                String Info[] = tmp.split(";");
                Label_htmmsv.setText(mssv);
                Label_hthoten.setText(Info[0]);
                Label_htPhái.setText(Info[1]);
                Label_htnoisinh.setText(Info[2]);
                Label_htnganh.setText(Info[3]);
                Label_htlop.setText(Info[4]);
                Label_htKhoa.setText(Info[5]);
                String Statistic = cliensocket.getStatistic(cliensocket.in, cliensocket.out);
                String count = cliensocket.getCount(cliensocket.in, cliensocket.out);
                String stat[] = Statistic.split(";");
                //Label_tbhe10.setText(stat[0]);
                //Label_tbhe4.setText(stat[1]);
                // lấy dư :))
                Label_tbtichluy.setText(stat[2]);
                Label_TCtichluyhe4.setText(stat[3]);
                Label_TCtichluy.setText(stat[4]);
                jLabelChidanghoc.setText(stat[5]);
                jLabelChiconlai.setText(stat[6]);
                Label_Somondahoc.setText(count);

                ArrayList<String> result = cliensocket.getResult(cliensocket.in, cliensocket.out);

                String[] d = null;
                DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
                model.getDataVector().removeAllElements();
                for (String rs : result) {
                    d = rs.split(": ");
                    Object[] row = {d[0], d[1]};
                    model.addRow(row);
                }
            }
            //}
        } catch (IOException ex) {
            Logger.getLogger(De5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_xemActionPerformed

    private void TextFile_mssvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFile_mssvActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TextFile_mssvActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
        jTable1.getTableHeader();
    }//GEN-LAST:event_jTable1ComponentShown

    private void jTextField_mssvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mssvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mssvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String masSv = jTextField_mssv.getText();
        String tieuchixephang = tieuChi.getSelectedItem().toString();
        if (tieuchixephang.equals("Chọn tiêu chí")) {
            tieuchixephang = "all";
        }
        try {
//            String dataClient = masSv + ";" + tieuchixephang;
            String dataClient = "button2#" + masSv + ";" + tieuchixephang;
            cliensocket.out.write(dataClient);
            cliensocket.Sent(cliensocket.out);
            if (cliensocket.check(cliensocket.in).equals("404")) {
                JOptionPane.showMessageDialog(null, "Mã số sinh viên không tồn tại");
            } else {
//                System.out.println(cliensocket.getPosition(cliensocket.in));
                if(tieuchixephang.equals("all")){
                    tieuchixephang = "Toàn trường";
                }
                jLabelCondition.setText(tieuchixephang);
                jLabelPosition.setText(cliensocket.getPosition(cliensocket.in));
 
                ArrayList<String> studentLower = cliensocket.getStudent(cliensocket.in, cliensocket.out, cliensocket.stdIn);
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.getDataVector().removeAllElements();
                for (String student : studentLower) {
                    String [] temp = student.split(":");
                    Object[] row = {temp[0], temp[1]};
                    model.addRow(row);
                }
                DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
                model2.getDataVector().removeAllElements();
                ArrayList<String> studentHigher = cliensocket.getStudent(cliensocket.in, cliensocket.out, cliensocket.stdIn);
                for (String student : studentHigher) {
                    String [] temp = student.split(":");
                    Object[] row = {temp[0], temp[1]};
                    model2.addRow(row);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(De5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tieuChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieuChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tieuChiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(De5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(De5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(De5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(De5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                De5 jframe = null;
                try {
                    jframe = new De5();
                } catch (IOException ex) {
                    Logger.getLogger(De5.class.getName()).log(Level.SEVERE, null, ex);
                }
                jframe.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_xem;
    private javax.swing.JLabel Label_Somondahoc;
    private javax.swing.JLabel Label_TCtichluy;
    private javax.swing.JLabel Label_TCtichluyhe4;
    private javax.swing.JLabel Label_htKhoa;
    private javax.swing.JLabel Label_htPhái;
    private javax.swing.JLabel Label_hthoten;
    private javax.swing.JLabel Label_htlop;
    private javax.swing.JLabel Label_htmmsv;
    private javax.swing.JLabel Label_htnganh;
    private javax.swing.JLabel Label_htnoisinh;
    private javax.swing.JLabel Label_mssv;
    private javax.swing.JLabel Label_tbtichluy;
    private javax.swing.JTextField TextFile_mssv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelChiconlai;
    private javax.swing.JLabel jLabelChidanghoc;
    private javax.swing.JLabel jLabelCondition;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabel_NoiSinh;
    private javax.swing.JLabel jLabel_hoten;
    private javax.swing.JLabel jLabel_lop;
    private javax.swing.JLabel jLabel_mssv;
    private javax.swing.JLabel jLabel_nganh;
    private javax.swing.JLabel jLabel_phai;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_tracuu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField_mssv;
    private javax.swing.JLabel jlabel_khoa;
    private javax.swing.JComboBox tieuChi;
    // End of variables declaration//GEN-END:variables
}
